### ISSUE TITLE
Travel times from/to the same ID is sometimes non-zero

### ISSUE THREAD

**Issue by ethan-moss** [r5py/r5py#254]
**Describe the bug**
When computing travel time matrices using `compute_travel_times()`  on a `TravelTimeMatrixComupter()` object, the travel times from/to the same ID are sometimes non-zero.

**To Reproduce**
1. Collect input pbf/GTFS data for the [Helsinki demo](https://github.com/r5py/r5py/tree/main/docs/data/Helsinki).
2. Follow the usage example in the [r5py docs](https://r5py.readthedocs.io/en/stable/notebooks/basic-usage.html), in particular [this section](https://r5py.readthedocs.io/en/stable/notebooks/basic-usage.html#compute-travel-time-matrix-from-one-to-all-locations) which calculates the travel times to/from all points.
3. Look for rows where the `from_id` and `to_id` are the same and `travel_time` is non-zero, e.g.
```
travel_time_matrix[(travel_time_matrix.from_id == travel_time_matrix.to_id) & (travel_time_matrix.travel_time != 0)]
```
4. Some rows are then returned where the start/end points are the same, but the travel times are non-zero.

**Expected behavior**
Travel times to/from the same point would always be 0.

**Environment:**
- OS: macOS Monterey v12.6
- Python package source: pypi/pip
- Python version: 3.9.16
- Java: AdoptOpenJDK 11.0.11+9

**Additional context**
I have tried an alternative .pbf/GTFS source and this observation remains. I have also tried various combinations of transit/walk and the issue is also present there too. Finally, as a preprocessing step, I extracted the node coordinates from the OSM file using `osmium` and I have snapped my origin/destination points to the closest OSM node and then re-run. This behaviour remained present in this case.

**Test data and/or script/notebook**
This behaviour was first observed using the [Helsinki demo](https://github.com/r5py/r5py/tree/main/docs/data/Helsinki) and code written in the [r5py docs usage page](https://r5py.readthedocs.io/en/stable/notebooks/basic-usage.html).

**Comment by christophfink** [comment]
@ethan-moss 

I found a race condition that caused the routing request to sometimes be rewritten before it was evaluated on the R5 side. 
In the (very limited) test case I built myself, I now don’t receive any travel times > 0 for from_id == to_id. 

Could you please test this change with your test case?

To install the pull request version, use (compare https://pip.pypa.io/en/stable/topics/vcs-support/#git):

```
pip install git+https://github.com/r5py/r5py.git@refs/pull/258/head
```

You might want to do this in a new virtual environment to keep things clean (although pip should support downgrading/reinstalling packages again

**Comment by ethan-moss** [comment]
@christophfink - thanks for looking into this! I've run some experiments, and the issue seems to have been resolved:

1. Walking only mode, raw origin/destinations (not snapped to OSM nodes), 7 repeats: Results are deterministic (all the same). Only a few cases where to/from the same ID were non-zero, but all of these were just 1 minute which would agree well with r5 just snapping the point to the network.
2. Repeating experiment 1, but instead using origin/destination points snapped to OSM nodes in pre-processing: Results are deterministic. Fewer points had non-zero to/from same ID than experiment 1 -> suggests it's snapping related. Again, the remaining points had only 1min travel time (side note: I've put the same data through OTP's one-to-many functionality and the same points have small non-zero travel time, so it's consistent and likely to do with the actual points themselves relative to the OSM network).
3. Repeating experiment 2, but in transit mode with GTFS inputs: Results are deterministic, and the same points in experiment 2 had 1min to/from same id travel times.

So similar to your test case, I would say it seems the issue has been resolved with the understanding the r5 does some minor snapping to the OSM network that could contribute small non-zero travel times.

However, when computing the travel time matrix it did throw this error:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mapdb.Volume$ByteBufferVol (file:.../.cache/r5py/r5-v6.9-all.jar) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.mapdb.Volume$ByteBufferVol
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
dyld[27759]: terminating because inserted dylib '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' could not be loaded: tried: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' (no such file), '/usr/local/lib/libjsig.so' (no such file), '/usr/lib/libjsig.so' (no such file)
dyld[27759]: tried: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' (no such file), '/usr/local/lib/libjsig.so' (no such file), '/usr/lib/libjsig.so' (no such file)
.../lib/python3.9/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
  warnings.warn('resource_tracker: process died unexpectedly, '
dyld[27760]: terminating because inserted dylib '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' could not be loaded: tried: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' (no such file), '/usr/local/lib/libjsig.so' (no such file), '/usr/lib/libjsig.so' (no such file)
dyld[27760]: tried: '/Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home/lib/jli/libjsig.so' (no such file), '/usr/local/lib/libjsig.so' (no such file), '/usr/lib/libjsig.so' (no such file)
```
The reflective access warning was present previously, but the 'multiprocessing/process died unexpectedly' warnings are new. Although, does not seem to affect the performance or the results in this case - the travel time matrix is returned. Is this expected? Do you know of a way to resolve the warning?

Also, the results in these experiments now seem to be deterministic. It may need more testing, but could this fix also contribute to resolving #240?

**Comment by christophfink** [comment]
Thanks so much! It’s promising that the issue has become so much smaller after this change. Going into the right direction.

If you could do a bit more testing concerning #240, that would be fantastic!

**Comment by christophfink** [comment]
The reflective access warning is, indeed, something that has to be dealt with upstream, we also did not manage to hide it from the Python console. Not sure how to deal with it, but it’s low priority right now

**Comment by christophfink** [comment]
But definitely curious about the ‘process died unexpectedly’ errors. They also starting cropping up on our test runners here in the GitHub Action/continuous testing - but they are really random, and re-running failed workflows would always lead to them passing. Because of this, I assumed it’s a glitch in the GitHub MacOS virtual machines (see #243), but apparently, you also ran into them on bare-metal MacOS - that means we actually have to look into these

**Comment by christophfink** [comment]
And then finally, also the missing `libjsig.so` has been cropping up on the MacOS test runners, and I’ve not come around to figure this out properly (the file might not be in the same location on all different JVM installations, so this will be quite tedious debugging)

I’ll update the issue #243 to reflect that this is not just a CI/CD runner issue, and add new ones about the warnings and `libjsig`, probably tomorrow morning. I might come back to you with more detailed questions, if that’s alright

**Comment by ethan-moss** [comment]
No problem at all - a bigger thanks to you for looking into the root cause :-).

The worst case I have seen so far is just 1 minute and this was  in <1% of origin/destinations, and snapping to OSM nodes during preprocessing resolved most of those. If it's possible to demonstrate the remaining small non-zero cases are due to some small snaps being done by r5 behind the scenes, then I would say the issue seems to be resolved. What do you think? Similarly, tomorrow morning I'll share the .pbf/GTFS/points data I'm using so you can replicate the small 1 min cases.

Thanks for sharing #243 - it's interesting that this isn't just on my end, but instead seems specific to some flavour of macOS. It is slightly different on my machine though, since the warnings are thrown every time as opposed to being random. At this early stage of the investigation, do you know if this warning affects the validity of the returned results in any way? Is there anything I should be cautious of in terms of potential resource leaks? Sure thing, very happy to help out, just let me know.

**Comment by christophfink** [comment]
> If it's possible to demonstrate the remaining small non-zero cases are due to some small snaps being done by r5 behind the scenes, then I would say the issue seems to be resolved. What do you think? 

I just wrote some code for using R5’s snapping (which operates on its internal network representation), it would be great to still test it with that one, to see whether we can get rid of these 1 min travel times, even.

> At this early stage of the investigation, do you know if this warning affects the validity of the returned results in any way? Is there anything I should be cautious of in terms of potential resource leaks? Sure thing, very happy to help out, just let me know.

Honestly, no idea. My general feeling would be to fix this properly, rather than investigate its potential for damage. Ironically, this is connected to making Java complain less about being run from within Python (and not having direct control of its signal handlers)

**Comment by christophfink** [comment]
> > If it's possible to demonstrate the remaining small non-zero cases are due to some small snaps being done by r5 behind the scenes, then I would say the issue seems to be resolved. What do you think?
> 
> I just wrote some code for using R5’s snapping (which operates on its internal network representation), it would be great to still test it with that one, to see whether we can get rid of these 1 min travel times, even.

I merged this into here. Could try to repeat your test case, and instantiate the `TravelTimeMatrix` with  `snap_to_network=True`?

Thanks!

**Comment by christophfink** [comment]
I added a test in 123ca9a to ensure walking time between a point and itself is zero

**Comment by ethan-moss** [comment]
@christophfink - thanks for that. I have tried the 'snap_to_network` argument but unfortunately it does not resolve issue with the data I'm using. I am still seeing travel times to/from the same ID sometimes being non-zero. When using the raw origin coordinates, it has reduced the number of non-zero travel times down from 3 to 1. When snapping the points to the OSM network during pre-processing, there is no change when using `snap_to_network` (remains at 1). In both cases, any non-zero travel times are always just 1 minute (same as before).

**Comment by christophfink** [comment]
@ethan-moss: do you encounter these non-zero times also in r5r or R5? Or is this, still, an r5py-specific problem?

**Comment by christophfink** [comment]
Thanks!
