### ISSUE TITLE
IllegalArgumentException: Geographic extent of street layer exceeds limit of 975000 km2.

### ISSUE THREAD

**Issue by fbarbe00** [r5py/r5py#447]
See https://github.com/ipeaGIT/r5r/issues/272 (same issue for r5r) and https://github.com/conveyal/r5/issues/815 (issue in r5 - fixed)

It seems that this was a hardcoded value in r5, and it seems it has been fixed. Would it be possible to merge the fix in r5py/r5?

Thanks!

**Comment by christophfink** [comment]
Hi Fabio, thanks for reporting this.

This issue should be already fixed in `main`, could you try it? (install r5py using `pip install --upgrade pip+https://github.com/r5py/r5py.git`)
If that works I probably find time for a quick release tomorrow

**Comment by fbarbe00** [comment]
I've run the command (watch out for the typo, should be `git+` instead of pip+) on the latest version.
```py
r5py.__version__ #'1.0.0dev0'
```

I still get `Geographic extent of street layer (9002132 km2) exceeds limit of 975000 km2.`. I'm trying to load data for all of Europe. My pbf file does not contain the entire map of Europe, but instead combined data of small clusters around stations around Europe. It weights ~70Mb.

**Comment by fbarbe00** [comment]
From my understanding, this value (975000 km2) is purely hardcoded. As written above my street layer is very large (9002132 km2), but only contains little data around train stations in Europe, so most of the map is empty, so I would expect to be able to load it into memory.

**Comment by christophfink** [comment]
Oh, so your street layer's geographical extent is, in fact, even larger than the increased limit (it used to be at 250_000km²). Since we allow for custom R5 jars, you could use a patched version with an even larger extent limit. I'll try something out, give me a moment

**Comment by fbarbe00** [comment]
I have not had time to look at the R5 code or try to build the jar myself, but did I understand correctly that that value is only there to limit users uploading large files on Conveyal's proprietary service? Therefore, can't it be removed completely in the custom build here?

**Comment by christophfink** [comment]
Precisely. I'd prefer increasing the value to an area larger than Earth's surface (as that is a smaller patch set than removing the checks).

I compiled an R5 jar with increased limits (1_000_000 km² for now). Could you download it from [here](https://github.com/r5py/r5/packages/1997579) (choose the file `r5-v7.3-r5py-1-g88de710-all.jar`), and follow the instructions at https://r5py.readthedocs.io/en/stable/user-guide/user-manual/advanced-use.html#use-a-custom-installation-of-r5 to try out your analysis using this patched version of R5?

**Comment by fbarbe00** [comment]
Thank you so much for the response! I'm now getting this error: `java.lang.ArrayIndexOutOfBoundsException: java.lang.ArrayIndexOutOfBoundsException: Attempt to seek beyond end of edge store`. It could very well be that there is an issue in my osm.pbf file, since another file from geofabrik seems to work fine, do you have any idea of what that could be?

**Comment by christophfink** [comment]
Hm, not sure to be honest, but I'd guess it's something about the osm.pbf file

**Comment by christophfink** [comment]
The issue is somehow similar to #277, isn't it?

**Comment by christophfink** [comment]
This has been resolved upstream: https://github.com/conveyal/r5/issues/815
